# Crawling Portal Tugas Akhir Universitas Trunojoyo Madura

In [ ]:
!pip install builtwith

Collecting builtwith
  Downloading builtwith-1.3.4.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from builtwith) (1.17.0)
Building wheels for collected packages: builtwith
  Building wheel for builtwith (setup.py) ... done
  Created wheel for builtwith: filename=builtwith-1.3.4-py3-none-any.whl size=36077 sha256=90e3d47b2d35c850d07effa11971ecd8ebc660560a3f44dd2d25d5e62bf01f0f
  Stored in directory: /root/.cache/pip/wheels/7f/2d/b2/606e3df914d4aeeab99c4a4e3e9a61673d2293c2e346db00c8
Successfully built builtwith
Installing collected packages: builtwith
Successfully installed builtwith-1.3.4

In [ ]:
import builtwith

# Analisis teknologi yang digunakan
res = builtwith.parse('https://pta.trunojoyo.ac.id')
print(res)

{'web-servers': ['Nginx'], 'javascript-frameworks': ['jQuery', 'jQuery UI']}

##Crawling Link Dataset

In [ ]:
import requests
from bs4 import BeautifulSoup

def crawl_website(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an error for bad status codes

        soup = BeautifulSoup(response.content, 'html.parser')

        # Ambil semua judul h1, h2, h3
        headings = soup.find_all(['h1', 'h2', 'h3'])
        for heading in headings:
            print(f"{heading.name}: {heading.get_text()}")

        # Ambil semua link
        links = soup.find_all('a', href=True)
        for link in links:
            print(f"URL: {link['href']} | Teks: {link.get_text()}")

    except requests.exceptions.RequestException as e:
        print(f"Terjadi kesalahan saat mengakses {url}: {e}")

# Gunakan fungsi
crawl_website("https://pta.trunojoyo.ac.id/")

h2: Daftar Karya Ilmiah
URL: index.html | Teks:
URL: # | Teks: 14677Journal
URL: https://pta.trunojoyo.ac.id/ | Teks: Beranda
URL: https://pta.trunojoyo.ac.id/c_search/ | Teks: Pencarian
URL: https://pta.trunojoyo.ac.id/c_template/ | Teks: Download
URL: https://library.trunojoyo.ac.id/detil.php?id=23 | Teks: Petunjuk Upload
URL: https://pta.trunojoyo.ac.id/c_contact/ | Teks: Kontak
URL: # | Teks: STRATEGI PENGEMBANGAN MAKANAN DAN MINUMAN KHAS PULAU GILIGENTING GUNA MENDUKUNG PARIWISATA BERKELANJUTAN
URL: https://pta.trunojoyo.ac.id/welcome/detail/170361100003 | Teks: Selengkapnya
URL: # | Teks: PERUMUSAN SANKSI PIDANA BAGI MASYARAKAT SEKITAR HUTAN YANG MELAKUKAN PENCURIAN KAYU MILIK NEGARA DALAM UNDANG-UNDANG NOMOR 18 TAHUN 2013
URL: https://pta.trunojoyo.ac.id/welcome/detail/170111100053 | Teks: Selengkapnya
URL: # | Teks: Peran Teor Motivasi Herzberg Sebagai Mediator Self Efficacy, Lingkungan Kerja Dalam Meningkatkan Prestasi Kerja Pegawai ( Kantor Jasa Penilai Publik Guntur Eki Andri dan Rekan Kota Surabaya )
URL: https://pta.trunojoyo.ac.id/welcome/detail/160211100116 | Teks: Selengkapnya
URL: https://pta.trunojoyo.ac.id/welcome/index/2 | Teks: 2
URL: https://pta.trunojoyo.ac.id/welcome/index/3 | Teks: 3
URL: https://pta.trunojoyo.ac.id/welcome/index/2 | Teks: >
URL: https://pta.trunojoyo.ac.id/welcome/index/4893 | Teks: »
URL: https://pta.trunojoyo.ac.id/c_search/byfac/1 | Teks: Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byprod/1 | Teks: Ilmu Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byprod/24 | Teks: Magister Ilmu Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byfac/2 | Teks: Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byprod/2 | Teks: Teknologi Industri Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byprod/3 | Teks: Agribisnis
URL: https://pta.trunojoyo.ac.id/c_search/byprod/4 | Teks: Agroteknologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/5 | Teks: Ilmu Kelautan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/35 | Teks: Manajemen Sumberdaya Perairan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/37 | Teks: Magister Pengelolaan Sumber Daya Alam
URL: https://pta.trunojoyo.ac.id/c_search/byfac/3 | Teks: Ekonomi Dan Bisnis
URL: https://pta.trunojoyo.ac.id/c_search/byprod/6 | Teks: Ekonomi Pembangunan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/7 | Teks: Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byprod/8 | Teks: Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/21 | Teks: D3 Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/22 | Teks: Magister Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byprod/25 | Teks: Magister Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/26 | Teks: D3 Enterpreneurship
URL: https://pta.trunojoyo.ac.id/c_search/byprod/36 | Teks: Magister Ilmu Ekonomi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/41 | Teks: Doktor Ilmu Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byfac/4 | Teks: Teknik
URL: https://pta.trunojoyo.ac.id/c_search/byprod/9 | Teks: Teknik Industri
URL: https://pta.trunojoyo.ac.id/c_search/byprod/10 | Teks: Teknik Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/11 | Teks: Manajemen Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/19 | Teks: Teknik Multimedia Dan Jaringan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/20 | Teks: Mekatronika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/23 | Teks: Teknik Elektro
URL: https://pta.trunojoyo.ac.id/c_search/byprod/31 | Teks: Sistem Informasi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/32 | Teks: Teknik Mesin
URL: https://pta.trunojoyo.ac.id/c_search/byprod/33 | Teks: Teknik Mekatronika
URL: https://pta.trunojoyo.ac.id/c_search/byfac/5 | Teks: Ilmu Sosial Dan Ilmu Budaya
URL: https://pta.trunojoyo.ac.id/c_search/byprod/12 | Teks: Sosiologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/13 | Teks: Ilmu Komunikasi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/14 | Teks: Psikologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/15 | Teks: Sastra Inggris
URL: https://pta.trunojoyo.ac.id/c_search/byfac/6 | Teks: Keislaman
URL: https://pta.trunojoyo.ac.id/c_search/byprod/16 | Teks: Ekonomi Syariah
URL: https://pta.trunojoyo.ac.id/c_search/byprod/17 | Teks: Hukum Bisnis Syariah
URL: https://pta.trunojoyo.ac.id/c_search/byfac/7 | Teks: Ilmu Pendidikan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/18 | Teks: Pgsd
URL: https://pta.trunojoyo.ac.id/c_search/byprod/27 | Teks: Pendidikan Bhs Dan Sastra Indonesia
URL: https://pta.trunojoyo.ac.id/c_search/byprod/28 | Teks: Pendidikan Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/29 | Teks: Pendidikan Ipa
URL: https://pta.trunojoyo.ac.id/c_search/byprod/30 | Teks: Pgpaud
URL: https://pta.trunojoyo.ac.id/c_search/byprod/38 | Teks: Pendidikan Profesi Guru
URL: https://pta.trunojoyo.ac.id/c_search/byfac/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byprod/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byfac/100 | Teks: Pascasarjana
URL: https://pta.trunojoyo.ac.id/c_search/byprod/39 | Teks: Magister Pendidikan Dasar
URL: https://pta.trunojoyo.ac.id/c_search/byprod/40 | Teks: Doktor Pengelolaan Sumber Daya Alam
URL: https://pta.trunojoyo.ac.id/c_search/byfac/1 | Teks: Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byfac/2 | Teks: Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byfac/3 | Teks: Ekonomi Dan Bisnis
URL: https://pta.trunojoyo.ac.id/c_search/byfac/4 | Teks: Teknik
URL: https://pta.trunojoyo.ac.id/c_search/byfac/5 | Teks: Ilmu Sosial Dan Ilmu Budaya
URL: https://pta.trunojoyo.ac.id/c_search/byfac/6 | Teks: Keislaman
URL: https://pta.trunojoyo.ac.id/c_search/byfac/7 | Teks: Ilmu Pendidikan
URL: https://pta.trunojoyo.ac.id/c_search/byfac/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byfac/100 | Teks: Pascasarjana
URL: http://trunojoyo.ac.id | Teks: www.trunojoyo.ac.id
URL: http://e-journal.dikti.go.id | Teks: http://e-journal.dikti.go.id
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:

In [ ]:
import requests
from bs4 import BeautifulSoup

def crawl_website(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an error for bad status codes

        soup = BeautifulSoup(response.content, 'html.parser')

        # Ambil semua judul h1, h2, h3
        headings = soup.find_all(['h1', 'h2', 'h3'])
        for heading in headings:
            print(f"{heading.name}: {heading.get_text()}")

        # Ambil semua link
        links = soup.find_all('a', href=True)
        for link in links:
            print(f"URL: {link['href']} | Teks: {link.get_text()}")

    except requests.exceptions.RequestException as e:
        print(f"Terjadi kesalahan saat mengakses {url}: {e}")

# Gunakan fungsi
crawl_website("https://pta.trunojoyo.ac.id/welcome/index/2")

h2: Daftar Karya Ilmiah
URL: index.html | Teks:
URL: # | Teks: 14677Journal
URL: https://pta.trunojoyo.ac.id/ | Teks: Beranda
URL: https://pta.trunojoyo.ac.id/c_search/ | Teks: Pencarian
URL: https://pta.trunojoyo.ac.id/c_template/ | Teks: Download
URL: https://library.trunojoyo.ac.id/detil.php?id=23 | Teks: Petunjuk Upload
URL: https://pta.trunojoyo.ac.id/c_contact/ | Teks: Kontak
URL: # | Teks: ANALISIS KANDUNGAN TIMBAL (Pb) UDANG REBON (Acetes sp) HASIL TANGKAPAN DI PERAIRAN SOCCAH KABUPATEN BANGKALAN
URL: https://pta.trunojoyo.ac.id/welcome/detail/160351100011 | Teks: Selengkapnya
URL: # | Teks: Analisis Wacana Media Online Detik.com dalam Memberitakan Peristiwa Kerusuhan Mahasiswa Papua di Surabaya
URL: https://pta.trunojoyo.ac.id/welcome/detail/160521100059 | Teks: Selengkapnya
URL: # | Teks: DETEKSI OBJEK MANUSIA BERBASIS ONE STAGE DETECTOR MENGGUNAKAN ALGORITMA YOU ONLY LOOK ONCE VERSI 2 (YOLOv2)
URL: https://pta.trunojoyo.ac.id/welcome/detail/160411100044 | Teks: Selengkapnya
URL: https://pta.trunojoyo.ac.id/welcome/index/1 | Teks: <
URL: https://pta.trunojoyo.ac.id/welcome/index/ | Teks: 1
URL: https://pta.trunojoyo.ac.id/welcome/index/3 | Teks: 3
URL: https://pta.trunojoyo.ac.id/welcome/index/4 | Teks: 4
URL: https://pta.trunojoyo.ac.id/welcome/index/3 | Teks: >
URL: https://pta.trunojoyo.ac.id/welcome/index/4893 | Teks: »
URL: https://pta.trunojoyo.ac.id/c_search/byfac/1 | Teks: Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byprod/1 | Teks: Ilmu Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byprod/24 | Teks: Magister Ilmu Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byfac/2 | Teks: Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byprod/2 | Teks: Teknologi Industri Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byprod/3 | Teks: Agribisnis
URL: https://pta.trunojoyo.ac.id/c_search/byprod/4 | Teks: Agroteknologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/5 | Teks: Ilmu Kelautan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/35 | Teks: Manajemen Sumberdaya Perairan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/37 | Teks: Magister Pengelolaan Sumber Daya Alam
URL: https://pta.trunojoyo.ac.id/c_search/byfac/3 | Teks: Ekonomi Dan Bisnis
URL: https://pta.trunojoyo.ac.id/c_search/byprod/6 | Teks: Ekonomi Pembangunan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/7 | Teks: Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byprod/8 | Teks: Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/21 | Teks: D3 Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/22 | Teks: Magister Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byprod/25 | Teks: Magister Akuntansi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/26 | Teks: D3 Enterpreneurship
URL: https://pta.trunojoyo.ac.id/c_search/byprod/36 | Teks: Magister Ilmu Ekonomi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/41 | Teks: Doktor Ilmu Manajemen
URL: https://pta.trunojoyo.ac.id/c_search/byfac/4 | Teks: Teknik
URL: https://pta.trunojoyo.ac.id/c_search/byprod/9 | Teks: Teknik Industri
URL: https://pta.trunojoyo.ac.id/c_search/byprod/10 | Teks: Teknik Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/11 | Teks: Manajemen Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/19 | Teks: Teknik Multimedia Dan Jaringan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/20 | Teks: Mekatronika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/23 | Teks: Teknik Elektro
URL: https://pta.trunojoyo.ac.id/c_search/byprod/31 | Teks: Sistem Informasi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/32 | Teks: Teknik Mesin
URL: https://pta.trunojoyo.ac.id/c_search/byprod/33 | Teks: Teknik Mekatronika
URL: https://pta.trunojoyo.ac.id/c_search/byfac/5 | Teks: Ilmu Sosial Dan Ilmu Budaya
URL: https://pta.trunojoyo.ac.id/c_search/byprod/12 | Teks: Sosiologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/13 | Teks: Ilmu Komunikasi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/14 | Teks: Psikologi
URL: https://pta.trunojoyo.ac.id/c_search/byprod/15 | Teks: Sastra Inggris
URL: https://pta.trunojoyo.ac.id/c_search/byfac/6 | Teks: Keislaman
URL: https://pta.trunojoyo.ac.id/c_search/byprod/16 | Teks: Ekonomi Syariah
URL: https://pta.trunojoyo.ac.id/c_search/byprod/17 | Teks: Hukum Bisnis Syariah
URL: https://pta.trunojoyo.ac.id/c_search/byfac/7 | Teks: Ilmu Pendidikan
URL: https://pta.trunojoyo.ac.id/c_search/byprod/18 | Teks: Pgsd
URL: https://pta.trunojoyo.ac.id/c_search/byprod/27 | Teks: Pendidikan Bhs Dan Sastra Indonesia
URL: https://pta.trunojoyo.ac.id/c_search/byprod/28 | Teks: Pendidikan Informatika
URL: https://pta.trunojoyo.ac.id/c_search/byprod/29 | Teks: Pendidikan Ipa
URL: https://pta.trunojoyo.ac.id/c_search/byprod/30 | Teks: Pgpaud
URL: https://pta.trunojoyo.ac.id/c_search/byprod/38 | Teks: Pendidikan Profesi Guru
URL: https://pta.trunojoyo.ac.id/c_search/byfac/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byprod/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byfac/100 | Teks: Pascasarjana
URL: https://pta.trunojoyo.ac.id/c_search/byprod/39 | Teks: Magister Pendidikan Dasar
URL: https://pta.trunojoyo.ac.id/c_search/byprod/40 | Teks: Doktor Pengelolaan Sumber Daya Alam
URL: https://pta.trunojoyo.ac.id/c_search/byfac/1 | Teks: Hukum
URL: https://pta.trunojoyo.ac.id/c_search/byfac/2 | Teks: Pertanian
URL: https://pta.trunojoyo.ac.id/c_search/byfac/3 | Teks: Ekonomi Dan Bisnis
URL: https://pta.trunojoyo.ac.id/c_search/byfac/4 | Teks: Teknik
URL: https://pta.trunojoyo.ac.id/c_search/byfac/5 | Teks: Ilmu Sosial Dan Ilmu Budaya
URL: https://pta.trunojoyo.ac.id/c_search/byfac/6 | Teks: Keislaman
URL: https://pta.trunojoyo.ac.id/c_search/byfac/7 | Teks: Ilmu Pendidikan
URL: https://pta.trunojoyo.ac.id/c_search/byfac/99 | Teks: Mbkm
URL: https://pta.trunojoyo.ac.id/c_search/byfac/100 | Teks: Pascasarjana
URL: http://trunojoyo.ac.id | Teks: www.trunojoyo.ac.id
URL: http://e-journal.dikti.go.id | Teks: http://e-journal.dikti.go.id
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:
URL: # | Teks:

In [ ]:
!pip install requests
!pip install beautifulsoup4
import requests
from bs4 import BeautifulSoup
import pandas as pd

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [14]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from IPython.display import display

def ptaa():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak": [],
        "prodi": []
    }

    prodi_urls = {
        "Ilmu Hukum": "https://pta.trunojoyo.ac.id/c_search/byprod/1",
        "Magister Ilmu Hukum": "https://pta.trunojoyo.ac.id/c_search/byprod/24",
        "Teknologi Industri Pertanian": "https://pta.trunojoyo.ac.id/c_search/byprod/2",
        "Agribisnis": "https://pta.trunojoyo.ac.id/c_search/byprod/3",
        "Agroteknologi": "https://pta.trunojoyo.ac.id/c_search/byprod/4",
        "Ilmu Kelautan": "https://pta.trunojoyo.ac.id/c_search/byprod/5",
        "Manajemen Sumberdaya Perairan": "https://pta.trunojoyo.ac.id/c_search/byprod/35",
        "Magister Pengelolaan Sumber Daya Alam": "https://pta.trunojoyo.ac.id/c_search/byprod/37",
        "Ekonomi Pembangunan": "https://pta.trunojoyo.ac.id/c_search/byprod/6",
        "Manajemen": "https://pta.trunojoyo.ac.id/c_search/byprod/7",
        "Akuntansi": "https://pta.trunojoyo.ac.id/c_search/byprod/8",
        "D3 Akuntansi": "https://pta.trunojoyo.ac.id/c_search/byprod/21",
        "Magister Manajemen": "https://pta.trunojoyo.ac.id/c_search/byprod/22",
        "Magister Akuntansi": "https://pta.trunojoyo.ac.id/c_search/byprod/25",
        "D3 Enterpreneurship": "https://pta.trunojoyo.ac.id/c_search/byprod/26",
        "Magister Ilmu Ekonomi": "https://pta.trunojoyo.ac.id/c_search/byprod/36",
        "Doktor Ilmu Manajemen": "https://pta.trunojoyo.ac.id/c_search/byprod/41",
        "Teknik Industri": "https://pta.trunojoyo.ac.id/c_search/byprod/9",
        "Teknik Informatika": "https://pta.trunojoyo.ac.id/c_search/byprod/10",
        "Manajemen Informatika": "https://pta.trunojoyo.ac.id/c_search/byprod/11",
        "Teknik Multimedia Dan Jaringan": "https://pta.trunojoyo.ac.id/c_search/byprod/19",
        "Mekatronika": "https://pta.trunojoyo.ac.id/c_search/byprod/20",
        "Teknik Elektro": "https://pta.trunojoyo.ac.id/c_search/byprod/23",
        "Sistem Informasi": "https://pta.trunojoyo.ac.id/c_search/byprod/31",
        "Teknik Mesin": "https://pta.trunojoyo.ac.id/c_search/byprod/32",
        "Teknik Mekatronika": "https://pta.trunojoyo.ac.id/c_search/byprod/33",
        "Sosiologi": "https://pta.trunojoyo.ac.id/c_search/byprod/12",
        "Ilmu Komunikasi": "https://pta.trunojoyo.ac.id/c_search/byprod/13",
        "Psikologi": "https://pta.trunojoyo.ac.id/c_search/byprod/14",
        "Sastra Inggris": "https://pta.trunojoyo.ac.id/c_search/byprod/15",
        "Ekonomi Syariah": "https://pta.trunojoyo.ac.id/c_search/byprod/16",
        "Hukum Bisnis Syariah": "https://pta.trunojoyo.ac.id/c_search/byprod/17",
        "PGSD": "https://pta.trunojoyo.ac.id/c_search/byprod/18",
        "Pendidikan Bhs Dan Sastra Indonesia": "https://pta.trunojoyo.ac.id/c_search/byprod/27",
        "Pendidikan Informatika": "https://pta.trunojoyo.ac.id/c_search/byprod/28",
        "Pendidikan IPA": "https://pta.trunojoyo.ac.id/c_search/byprod/29",
        "PGPAUD": "https://pta.trunojoyo.ac.id/c_search/byprod/30",
        "Pendidikan Profesi Guru": "https://pta.trunojoyo.ac.id/c_search/byprod/38",
        "MBKM": "https://pta.trunojoyo.ac.id/c_search/byprod/99",
        "Magister Pendidikan Dasar": "https://pta.trunojoyo.ac.id/c_search/byprod/39",
        "Doktor Pengelolaan Sumber Daya Alam": "https://pta.trunojoyo.ac.id/c_search/byprod/40"
    }

    # looping semua prodi
    for nama_prodi, prodi_url in prodi_urls.items():
        for i in range(1, 6):  # 5 halaman per prodi
            url = f"{prodi_url}/{i}"
            r = requests.get(url)
            soup = BeautifulSoup(r.content, "html.parser")
            jurnals = soup.select('li[data-cat="#luxury"]')

            for jurnal in jurnals:
                response = requests.get(jurnal.select_one('a.gray.button')['href'])
                soup1 = BeautifulSoup(response.content, "html.parser")
                isi = soup1.select_one('div#content_journal')

                judul = isi.select_one('a.title').text.strip()

                penulis = isi.select_one('span:-soup-contains("Penulis")').text.split(' : ')[1].strip()
                pembimbing_pertama = isi.select_one('span:-soup-contains("Dosen Pembimbing I")').text.split(' : ')[1].strip()
                pembimbing_kedua = isi.select_one('span:-soup-contains("Dosen Pembimbing II")').text.split(' :')[1].strip()

                abstrak = isi.select_one('p[align="justify"]').text.strip()
                if abstrak == '':
                    abstrak = ' '.join(isi.find('p').findNext('p').stripped_strings).capitalize()

                data["penulis"].append(penulis)
                data["judul"].append(judul)
                data["pembimbing_pertama"].append(pembimbing_pertama)
                data["pembimbing_kedua"].append(pembimbing_kedua)
                data["abstrak"].append(abstrak)
                data["prodi"].append(nama_prodi)

    df = pd.DataFrame(data)
    df.to_csv("pta.csv", index=False)

    display(df)  # tampil rapi di notebook
    return df

In [15]:
ptaa()

/tmp/ipython-input-3855695588.py:81: DeprecationWarning: Call to deprecated method findNext. (Replaced by find_next) -- Deprecated since version 4.0.0.
  abstrak = ' '.join(isi.find('p').findNext('p').stripped_strings).capitalize()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak,prodi
0,Dyah Ayu Citra Seza,Implementasi Fungsi Legislasi Dewan Perwakilan...,"Yudi Widagdo Harimurti, SH., MH","Safi', SH., MH",ABSTRAK\r\n\r\n Implementasi Fungsi Legi...,Ilmu Hukum
1,Maulina Nurlaily,Pertanggungjawaban Pidana Direksi BUMN (Perser...,"Tolib Effendi, SH., MH.","Dr. Eni Suastuti, SH., Mhum.",Badan Usaha Milik Negara (BUMN) adalah Badan u...,Ilmu Hukum
2,Moh. Samsul Hidayat,Analisis Terhadap Kekosongan Hukum dalam Penga...,"Tolib Effendi, SH., MH.","Agus Ramdlany, SH., MH.",Kasus narkoba tidak henti-hentinya terdengar d...,Ilmu Hukum
3,TOMMY ADITYA PARLINDUNGAN MARBUN,PERLINDUNGAN HUKUM BAGI KONSUMEN ATAS PRODUK E...,"DR. DJULAEKA, S.H., M.HUM","DR.USWATUN HASANAH, S.H., M. HUM",Produk elektronik adalah suatu benda bergerak ...,Ilmu Hukum
4,RICA YENA IMADHORA,TELAAH KRITIS TENTANG ALASAN HUKUM YANG DIGUN...,"Dr. DENI SBY, S. H., M. S.","SAIFUL ABDULLAH, S. H., M. H.",,Ilmu Hukum
...,...,...,...,...,...,...
776,WIDYA SULISTIANI,PENGARUH BERENANG TERHADAP KETERAMPILAN MOTORI...,"Dewi Mayangsari, S.Psi., M. Psi, Psi.","M. Busyro Karim, S.Ag., M.si.",Tujuan penelitian ini adalah untuk mengetahui ...,PGPAUD
777,Siti Mardiyah,Pengaruh Metode Demonstrasi Terhadap Kemampuan...,"Siti Fadjryana Fitroh, S.Psi, MA","Dwi Nurhayati Adhani, S.Psi, M.Psi",Penelitian ini bertujuan untuk mengetahui peng...,PGPAUD
778,Riana Rahayu,Pengaruh Model Pembelajaran Koopatif Tipe Make...,"Siti Fadjryana Fitroh S. Psi., MA","Dewi Mayang Sari S.Psi.,M.Psi",Salah satu kemampuan yang sangat penting untuk...,PGPAUD
779,dwi astutik,pengaruh penggunaan metode karyawisata terhada...,"dewi mayang sari, S.Psi., M.Psi","siti fadjryana fitroh, S.Psi., MA",Tujuan dari penelitian ini untuk mengetahui pe...,PGPAUD
780,Ayu Ratna Pratiwi,Pengaruh Metode Bermain Dengan Bahan Bekas Ter...,"Siti Fadjiyana Fitroh, S.Psi., MA","Dwi Nurhayati Adhani, S.Psi., M.Psi",Tujuan dari penelitian adalah untuk mengetahui...,PGPAUD

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak,prodi
0,Dyah Ayu Citra Seza,Implementasi Fungsi Legislasi Dewan Perwakilan...,"Yudi Widagdo Harimurti, SH., MH","Safi', SH., MH",ABSTRAK\r\n\r\n Implementasi Fungsi Legi...,Ilmu Hukum
1,Maulina Nurlaily,Pertanggungjawaban Pidana Direksi BUMN (Perser...,"Tolib Effendi, SH., MH.","Dr. Eni Suastuti, SH., Mhum.",Badan Usaha Milik Negara (BUMN) adalah Badan u...,Ilmu Hukum
2,Moh. Samsul Hidayat,Analisis Terhadap Kekosongan Hukum dalam Penga...,"Tolib Effendi, SH., MH.","Agus Ramdlany, SH., MH.",Kasus narkoba tidak henti-hentinya terdengar d...,Ilmu Hukum
3,TOMMY ADITYA PARLINDUNGAN MARBUN,PERLINDUNGAN HUKUM BAGI KONSUMEN ATAS PRODUK E...,"DR. DJULAEKA, S.H., M.HUM","DR.USWATUN HASANAH, S.H., M. HUM",Produk elektronik adalah suatu benda bergerak ...,Ilmu Hukum
4,RICA YENA IMADHORA,TELAAH KRITIS TENTANG ALASAN HUKUM YANG DIGUN...,"Dr. DENI SBY, S. H., M. S.","SAIFUL ABDULLAH, S. H., M. H.",,Ilmu Hukum
...,...,...,...,...,...,...
776,WIDYA SULISTIANI,PENGARUH BERENANG TERHADAP KETERAMPILAN MOTORI...,"Dewi Mayangsari, S.Psi., M. Psi, Psi.","M. Busyro Karim, S.Ag., M.si.",Tujuan penelitian ini adalah untuk mengetahui ...,PGPAUD
777,Siti Mardiyah,Pengaruh Metode Demonstrasi Terhadap Kemampuan...,"Siti Fadjryana Fitroh, S.Psi, MA","Dwi Nurhayati Adhani, S.Psi, M.Psi",Penelitian ini bertujuan untuk mengetahui peng...,PGPAUD
778,Riana Rahayu,Pengaruh Model Pembelajaran Koopatif Tipe Make...,"Siti Fadjryana Fitroh S. Psi., MA","Dewi Mayang Sari S.Psi.,M.Psi",Salah satu kemampuan yang sangat penting untuk...,PGPAUD
779,dwi astutik,pengaruh penggunaan metode karyawisata terhada...,"dewi mayang sari, S.Psi., M.Psi","siti fadjryana fitroh, S.Psi., MA",Tujuan dari penelitian ini untuk mengetahui pe...,PGPAUD
780,Ayu Ratna Pratiwi,Pengaruh Metode Bermain Dengan Bahan Bekas Ter...,"Siti Fadjiyana Fitroh, S.Psi., MA","Dwi Nurhayati Adhani, S.Psi., M.Psi",Tujuan dari penelitian adalah untuk mengetahui...,PGPAUD

In [ ]:
import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse

# Konfigurasi
URL = "https://lisdalanchirasyahjian.github.io/PPW/intro.html"  # Website target
FOLDER_NAME = "gambar"             # Folder untuk simpan gambar
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
}

# Buat folder jika belum ada
if not os.path.exists(FOLDER_NAME):
    os.makedirs(FOLDER_NAME)
    print(f"Folder '{FOLDER_NAME}' berhasil dibuat.")

# Ambil halaman web
try:
    response = requests.get(URL, headers=HEADERS, timeout=10)
    response.raise_for_status()
except requests.exceptions.RequestException as e:
    print(f"Gagal mengakses {URL}: {e}")
    exit()

# Parse HTML dengan BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Cari semua tag <img>
images = soup.find_all('img')
print(f"Ditemukan {len(images)} gambar di halaman {URL}.")

# List untuk menyimpan URL gambar
image_urls = []

for i, img in enumerate(images):
    # Ambil atribut src
    src = img.get('src')
    if not src:
        print(f"Gambar ke-{i+1} tidak memiliki atribut 'src', dilewati.")
        continue

    # Konversi URL relatif ke absolut
    img_url = urljoin(URL, src)
    image_urls.append(img_url)

    # Ambil nama file dari URL
    parsed_url = urlparse(img_url)
    filename = os.path.basename(parsed_url.path)

    # Validasi nama file
    if not filename or '.' not in filename:
        ext = '.jpg'
        filename = f"image_{i+1}{ext}"

    # Pastikan ekstensi file valid
    valid_exts = ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg')
    if not filename.lower().endswith(valid_exts):
        filename += '.jpg'

    # Path lokal
    file_path = os.path.join(FOLDER_NAME, filename)

    # Download gambar
    try:
        img_response = requests.get(img_url, headers=HEADERS, timeout=10)
        img_response.raise_for_status()

        with open(file_path, 'wb') as f:
            f.write(img_response.content)

        print(f"Berhasil download: {filename} -> {file_path}")

    except Exception as e:
        print(f"Gagal download {img_url}: {e}")

# Ringkasan
print("\nCrawling selesai!")
print(f"Semua gambar disimpan di: ./{FOLDER_NAME}")
print(f"Total gambar diproses: {len(image_urls)}")

Folder 'gambar' berhasil dibuat.
Ditemukan 2 gambar di halaman https://lisdalanchirasyahjian.github.io/PPW/intro.html.
Berhasil download: foto.png -> gambar/foto.png
Berhasil download: foto.png -> gambar/foto.png

Crawling selesai!
Semua gambar disimpan di: ./gambar
Total gambar diproses: 2